spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis?characterEncoding=utf-8&userSSL=false
    username: root
    password: "0316"
    type: com.zaxxer.hikari.HikariDataSource
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #设置mybatisplus的全局配置
  global-config:
    db-config:
      #设置实体类对应表的统一前缀
      table-prefix: t_
      #设置统一的主键生成策略
      id-type: auto
  #配置类型别名所对应的包
  type-aliases-package: com.example.mybatisplus.pojo
  type-enums-package: com.example.mybatisplus.enums
