spring:
  #配置数据源信息
  datasource:
    dynamic:
      #设置默认的数据源或者数据源组，默认值为master
      primary: master
        #严格匹配数据源，默认false，true未匹配到指定时抛出异常，false使用默认数据源
      strict: false
      datasource:

        master:
          url: jdbc:mysql://localhost:3306/mybatis
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: "0316"

        slave_1:
          url: jdbc:mysql://localhost:3306/mybatis_plus_1
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: "0316"

